services:
    db:
        image: HCQ/mariadb
        build: ./database
        restart: always
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: notgood
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080