version: '3.7'

secrets:
  mariadb_root_password:
    external: true

volumes:
  hcq_db_data:
    external: true

services:
  db:
    image: hcq/mariadb:latest
    # build: ./database     # <-- ignored by Swarm; build & push your image ahead of time
    volumes:
      - hcq_db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    secrets:
      - mariadb_root_password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  web:
    image: hcq/web:latest
    # build: ./web           # <-- ignored by Swarm; build & push your image ahead of time
    volumes:
      - ./DATA_STORE/:/var/www/html/data
    ports:
      - "8888:8080"
    environment:
      - DB_PASSWORD_FILE=/run/secrets/mariadb_root_password
    secrets:
      - mariadb_root_password
    deploy:
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: any
